title: "Maxwell Kiptoo — Portfolio"
email: ""
description: >-
  Personal portfolio of Maxwell Kiptoo — BSc IT graduate, Ethical Hacker, Software Developer,
  Data Protection Officer, and IT Specialist based in Kenya.

twitter_username: ""
github_username: "maxwellkiptoo"
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Maxwell Kiptoo, BSc"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Information Technology Specialist • Ethical Hacker • Software Developer • Data Protection Officer."
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://maxwellkiptoo.github.io/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://ke.linkedin.com/in/maxwell-kiptoowebaite"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maxwellkiptoo"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://ke.linkedin.com/in/maxwell-kiptoowebaite"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/maxwellkiptoo"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
